rvm:
 - 1.9.3
 - 2.0.0
 - ruby-head
gemfiles:
  - gemfiles/Gemfile.rails-2.x
  - gemfiles/Gemfile.rails-3.x
  - Gemfile
notifications:
  recipients:
    - jarmo.p@gmail.com
matrix:
  allow_failures:
    - rvm: ruby-head

